### PR TITLE
Support to use a custom database number

### LINKED ISSUE #188: Anycable-go ignores Redis database number
**AnyCable-Go version:**
1.4.3-214a549

**AnyCable gem version:**
 anycable (1.4.1)
 
### What did you do?
We are using Anycable with a single-instance Redis, and it appears that Anycable-go ignores the Redis database number.

For clarity in the experiment, I ran only anycable-go with the following configuration:
```yml
    command: anycable-go --redis_url redis://redis:6379/3
    environment:
      REDIS_URL: redis://redis:6379/1
      ANYCABLE_REDIS_URL: redis://redis:6379/2
```

Based on the output of --help, it seems that the Redis URL is detected correctly(as it changes default to "redis://redis:6379/2"):
```bash
root@463e913b0612:/app# anycable-go --help | grep redis_url
   --redis_url value                          Redis url (default: "redis://redis:6379/2") [$ANYCABLE_REDIS_URL, $REDIS_URL]
```

I've looked onto [code](https://github.com/anycable/anycable-go/blob/bcf58fb09d6b5b5735d1dbb46458dbbf66b84af1/redis/redis.go#L182), and it seems it does not send SelectDB to rueidis, nor uses [ParseURL](https://github.com/redis/rueidis/blob/061235434ec84cc8442c1515c697791138052c2e/README.md#redis-url), and InitAddress contains only host, so it always connects to default database 0.

### What did you expect to happen?

Anycable-go uses database 2.

### What actually happened?

On the clear Redis instance it sets keys only for database 0.
```bash
/data # redis-cli -n 0
127.0.0.1:6379> KEYS *
1) "__anycable__"
127.0.0.1:6379> select 1
OK
127.0.0.1:6379[1]> KEYS *
(empty array)
127.0.0.1:6379[1]> select 2
OK
127.0.0.1:6379[2]> KEYS *
(empty array)
127.0.0.1:6379[2]> select 3
OK
127.0.0.1:6379[3]> KEYS *
(empty array)
127.0.0.1:6379[3]> select 4
OK
127.0.0.1:6379[4]> KEYS *
(empty array)
127.0.0.1:6379[4]> select 5
OK
127.0.0.1:6379[5]> KEYS *
(empty array)
127.0.0.1:6379[5]>
/data #
```

On the other side, gem anycable does change the database number depending on the url, and will create a key in a not default database.

Anycable-go logs:

```
DEBUG 2023-09-07T05:38:12.974Z context=main 🔧 🔧 🔧 Debug mode is on 🔧 🔧 🔧                                                                   [5/6804]
 INFO 2023-09-07T05:38:12.974Z context=main Starting AnyCable 1.4.3-214a549 (pid: 1, open file limit: 1048576, gomaxprocs: 8)                            
 INFO 2023-09-07T05:38:12.974Z context=main Anonymized telemetry is on. Learn more: https://docs.anycable.io/anycable-go/telemetry                       
 INFO 2023-09-07T05:38:12.974Z context=main Using in-memory broker (epoch: yR3N, history limit: 5000, history ttl: 20s, sessions ttl: 300s)              
DEBUG 2023-09-07T05:38:12.974Z context=disconnector Calls rate: 10ms                                                                                     
 WARN 2023-09-07T05:38:12.974Z context=main Using a non-distributed broadcaster without a pub/sub enabled; each broadcasted message is only processed by a single node
 INFO 2023-09-07T05:38:12.974Z consumer=Zir5Yw context=broadcast id=Zir5Yw provider=redisx stream=__anycable__ Starting Redis broadcaster at redis:6379
 INFO 2023-09-07T05:38:12.975Z context=rpc RPC controller initialized: localhost:50051 (concurrency: 28, impl: grpc, enable_tls: false, proto_versions: v

 INFO 2023-09-07T05:38:12.975Z context=main Handle WebSocket connections at http://0.0.0.0:8080/cable
 INFO 2023-09-07T05:38:12.975Z context=main Handle health requests at http://0.0.0.0:8080/health
DEBUG 2023-09-07T05:38:12.975Z context=main Go pools initialized (remote commands: 256)
DEBUG 2023-09-07T05:38:12.975Z context=http Starting WebSocket server at http://0.0.0.0:8080
DEBUG 2023-09-07T05:38:12.975Z context=metrics No metrics writers. Disable metrics rotation
```

### PR DESCRIPTION
**Pull request by ardecvz**
### What is the purpose of this pull request?
Support to use a custom database number.
### What changes did you make? (overview)
Parse `--redis_url` (`ANYCABLE_REDIS_URL` or `REDIS_URL`) using the `rueidis` standard utility.
### Is there anything you'd like reviewers to focus on?
**WARNING!** This could be a potentially breaking change. Prior to this update, AnyCable Go did not support database numbers but allowed them in the `REDIS_URL`. As a result, if a user had set a URL with a database number, all data would still be written to the default database (`0`). After upgrading, this will break the existing user setup by starting to write data to the specified in the URL database, potentially leaving remnants in the old one.

@palkan, it's critical for you to assess how important the data in the storage is and decide on the appropriate path for data migration (whether that be discarding the old data, issuing a warning, performing automatic migration, etc.).
### Checklist

- [x] I've added tests for this change
- [x] I've added a Changelog entry
- [x] I've updated documentation

Fixes #188

### CODE REVIEW

**Comment by ardecvz** [comment]
@palkan The extended test conformance output is fixed there - https://github.com/anycable/anyt/pull/7
Anyway, I'm looking into the failures.

**Comment by ardecvz** [comment]
Locally no errors with NATS and NATS Embedded

**Comment by ardecvz** [comment]
It seems that the hidden errors are timeouts - `Anyt::Client::TimeoutError`
I've reproduced errors locally with another conformance suite (`https`), but it seems to be broken in the master too :'(

**Comment by palkan** [comment]
> Locally no errors with NATS and NATS Embedded

Have you tried upgrading `nats-pure`?) (I guess, @Envek knows what happened 😁)

**Comment by palkan** [comment]
Thanks! I pinned `nats-pure` to an older version for now. Merging this and hope all tests will pass now.

**Comment by palkan** [comment]
Okay, this is a real one: https://github.com/anycable/anycable-go/actions/runs/6154293794/job/16699510933

@ardecvz Could you please take a look? (And propose a follow-up PR?)

**Comment by ardecvz** [comment]
Of course, NATS hides these failures. 
And did you see the WARNING in the PR description?
This change may break user setups when we're starting to use the proper database number - is it OK to lose data remnants there?

**Pull request merged**
