### PR TITLE
[WIP] Project structure refactoring

### PR DESCRIPTION
**Pull request by sponomarev**
Hey, @palkan! Which one is the best: small incremental changes and merges or a major one-time change?

### CODE REVIEW

**Comment by palkan** [comment]
Hi!

Let's create a new branch for refactoring and use it as a base for small changes.

**Comment by palkan** [comment]
Add `restructure` branch.

**Comment by palkan** [comment]
Btw, why https://github.com/op/go-logging?

I was thinking about https://github.com/sirupsen/logrus. It has a lot of plugins and [testing support](https://github.com/sirupsen/logrus#testing) (that's awesome!).

**Comment by sponomarev** [comment]
@palkan Who knows, it was you who decided to use it. I'll be glad to remove it with a testable one.

**Comment by sponomarev** [comment]
Closing in favor of full logging system refactoring

**Pull request closed without merging**
